# General Travis config
sudo: required
services:
  - docker
language: python
python:  # Only one version for now
  - "2.7"
cache: pip

before_install:
  - travis_retry pip install -U pip
  - pip --version
install:
  - travis_retry pip install tox
  - tox --version
script:
  - travis_retry tox -v

# Test matrix will be constructed from here. Listing out each set of tests
# to execute will permit them to be executed in parallel
env:
  - TOXENV=lint
  - TOXENV=docs
  - TOXENV=py27
  - TOXENV=cent6_slave
  - TOXENV=cent7_slave
  - TOXENV=fedora_slave
  - TOXENV=cent7_master

deploy:
  - provider: pypi
    repo: RedHatQE/cinch
    user: "${PYPI_USER}"
    password: "${PYPI_PASSWORD}"
    distributions: "sdist bdist_wheel"
    on:
      tags: true
      condition: $TEST = lint.sh
  - provider: script
    repo: RedHatQE/cinch
    script: ./scripts/deploy.sh centos6 false
    on:
      tags: true
      condition: $TEST = cent6_slave.sh
  - provider: script
    repo: RedHatQE/cinch
    script: ./scripts/deploy.sh centos7 true
    on:
      tags: true
      condition: $TEST = cent7_slave.sh
  - provider: script
    repo: RedHatQE/cinch
    script: ./scripts/deploy.sh fedora25 false
    on:
      tags: true
      condition: $TEST = fedora_slave.sh
