# General Travis config
sudo: required
services:
  - docker
language: python
python: # Only one version for now
    - "2.7"
cache: pip

# Installation of the system
addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck
install:
  - tests/install.sh
script:
  - tests/${TEST}

# Test matrix will be constructed from here. Listing out each set of tests
# to execute will permit them to be executed in parallel
env:
    - TEST=lint.sh
    - TEST=docs.sh
    - TEST=coverage.sh
    - TEST=cent6_slave.sh
    - TEST=cent7_slave.sh
    - TEST=fedora_slave.sh

deploy:
  - provider: pypi
    repo: RedHatQE/cinch
    user: "${PYPI_USER}"
    password: "${PYPI_PASSWORD}"
    distributions: "sdist bdist_wheel"
    on:
      tags: true
      condition: $TEST = lint.sh
  - provider: script
    repo: RedHatQE/cinch
    script: ./scripts/deploy.sh centos6 false
    on:
      tags: true
      condition: $TEST = cent6_slave.sh
  - provider: script
    repo: RedHatQE/cinch
    script: ./scripts/deploy.sh centos7 true
    on:
      tags: true
      condition: $TEST = cent7_slave.sh
