# Local path to a private SSH keyfile to upload into the remote system and
# to set as an authorized keyfile for the Jenkins user
jenkins_ssh_keyfile: id_rsa
# The Java version to install. Older versions are deprecated and will not be
# supported beyond the EOL support for their packages in the distribution of
# choice
java_version: 8
# Needed for certain OpenShift instances
jenkins_user_uid: 1000090000
# Set the default (empty) set of authorized SSH public keys for jenkins user.
# To add authorized keys, override this value by adding a list of paths
# (relative or full) to files containing separate public keys.
# e.g.: ['mykey.pub', 'otherkey.pub']
jenkins_authorized_keys: []
