- name: construct command line for SSH check
  set_fact:
    check_ssh_cmd: >-
      ansible --ssh-extra-args='-o StrictHostKeyChecking=no'
      -i {{ inventory_dir }}/{{ inventory_file | basename }}
      {{ host }} -m ping

- name: check for SSH connectivity and authentication
  local_action: shell {{ check_ssh_cmd }}
  register: result
  changed_when: "result.rc != 0"
  until: result.rc == 0
  retries: "{{ ssh_retries }}"
  delay: "{{ ssh_retry_delay }}"
  when: "'{{ ansible_connection }}' == 'ssh'"
