# These are arguments which you will need to override
# URL for the Jenkins master this slave should attach to
jenkins_url: http://example.com:8080/jenkins/

# The Jenkins name for the slave
jslave_name: "{{ inventory_hostname }}"
# The label for this slave
jslave_label: ops-jslave
# Number of executor processes on the slave - modify based on system capacity and load
jswarm_execs: 10
# Extra command line args passed to jswarm
jswarm_extra_args: ''
# Directory where the swarm will live and execute
jswarm_home: "{{ jenkins_user_home }}"
# Whether the swarm should execute as the jenkins user. False means it will exec as root
run_swarm_as_jenkins: false
# Path to Java interpreter to use to run the Swarm client
jenkins_java_cmd: /usr/bin/java
# Command line args to the Java executable, such as heap size, etc
java_args: -Xmx2048m

# These are variables which you probably don't want to
# override, but which you are free to override if you
# feel the need to
jswarm_download: "http://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/\
  {{ jswarm_version }}/{{ jswarm_filename }}"
jswarm_local_directory: /opt/jswarm
jenkins_slave_username: ''
jenkins_slave_password: ''

# These are variables that you really should not override
# unless you really know what you're doing
jslave_rpm_deps:
  - python-paramiko
  - git
  - gcc
  - krb5-workstation
  - wget
  - python-pip
  - python-unittest2
  - python-pep8
  # This package is not available in RHEL6
  # TODO: fix
  # - python-flake8
  - python-futures
  - python-devel
  - nss
  - redhat-rpm-config
